import Detail from "@/components/Detail";
import postRepository from "@/repositories/Post/post.repository";
import { NextPageContext } from "next";
import Head from "next/head";
import React from "react";
import { dehydrate, QueryClient } from "react-query";

const DetailPage = () => {
  return (
    <>
      <Head>
        <title>멘투멘</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Detail />
    </>
  );
};

DetailPage.getInitialProps = async (ctx: NextPageContext) => {
  const queryClient = new QueryClient();

  if (ctx.query.id) {
    await Promise.all([
      queryClient.prefetchQuery(["post/read-one", Number(ctx.query.id)], () =>
        postRepository.getPostById(Number(ctx.query.id))
      ),
    ]);
  }

  return {
    id: ctx.query.id as string,
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default DetailPage;
