import useHideHeaderOrNav from "@/src/hooks/common/useHideHeaderOrNav";
import flex from "@/src/styles/flex";
import Head from "next/head";
import styled from "styled-components";

const NotFound = () => {
  useHideHeaderOrNav("Both");

  return (
    <>
      <Head>
        <title>멘투멘 | 존재하지 않는 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, maximum-scale=10" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>404 - 존재하지 않는 페이지입니다.</Container>
    </>
  );
};

export default NotFound;

const Container = styled.div`
  width: 100%;
  height: 95vh;
  ${flex({ alignItems: "center", justifyContent: "center" })}
`;
