import Home from "@/src/components/Home";
import { QUERY_KEYS } from "@/src/queries/queryKey";
import postRepository from "@/src/repositories/Post/post.repository";
import Head from "next/head";
import { dehydrate, QueryClient } from "react-query";

const HomePage = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 메인 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await Promise.all([
    queryClient.prefetchQuery(
      QUERY_KEYS.Post.getList,
      postRepository.getAllPost
    ),
  ]);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default HomePage;
