import Head from "next/head";
import { dehydrate, QueryClient } from "react-query";
import MyPage from "../components/MyPage";
import { QUERY_KEYS } from "../constants/Auth/auth.constant";
import UserApi from "../services/User/api";

const MyPagePage = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 마이 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, maximum-scale=10" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyPage />
    </>
  );
};

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await Promise.all([
    queryClient.prefetchQuery(QUERY_KEYS.User.getMyPost, UserApi.getMyPostApi),
  ]);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default MyPagePage;
