import Notification from "@/src/components/Notification";
import Head from "next/head";
import React from "react";
import { dehydrate, QueryClient } from "react-query";
import { QUERY_KEYS } from "../constants/Auth/auth.constant";
import NotificationApi from "../services/Notification/api";

const NotificationPage = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 알림 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, maximum-scale=10" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Notification />
    </>
  );
};

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await Promise.all([
    queryClient.prefetchQuery(
      QUERY_KEYS.Notice.getNoticeList,
      NotificationApi.getNoticeListApi
    ),
  ]);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default NotificationPage;
