import RequestMentor from "@/components/RequestMentor";
import Head from "next/head";

const RequestMentorPage = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 멘토 요청 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RequestMentor />
    </>
  );
};

export default RequestMentorPage;
