import RequestMentor from "@/src/components/RequestMentor";
import Head from "next/head";
import { useRouter } from "next/router";
import React from "react";

const ModifyPage = () => {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>멘투멘 | 멘토 요청 수정 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RequestMentor
        type={router.pathname === "/request-mentor/modify" ? "MODIFY" : "WRITE"}
      />
    </>
  );
};

export default ModifyPage;
