import Home from "@/components/Main/Home";
import postRepository from "@/repositories/Post/post.repository";
import Head from "next/head";
import { dehydrate, QueryClient } from "react-query";

const Index = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 메인 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
    </>
  );
};

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();
  await queryClient.prefetchQuery("list/useGetList", postRepository.getPost);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default Index;
