import { QUERY_KEYS } from "@/queries/queryKey";
import userRepository from "@/repositories/User/user.repository";
import Head from "next/head";
import { dehydrate, QueryClient } from "react-query";
import MyPost from "../components/MyPost";

const MyPostPage = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 마이 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MyPost />
    </>
  );
};

export const getServerSideProps = async () => {
  const queryClient = new QueryClient();

  await Promise.all([
    queryClient.prefetchQuery(
      QUERY_KEYS.User.getMyPost,
      userRepository.getMyPost
    ),
  ]);

  return {
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default MyPostPage;
