import Detail from "@/src/components/Detail";
import { QUERY_KEYS } from "@/src/constants/Auth/auth.constant";
import PostApi from "@/src/services/Post/api";
import { NextPageContext } from "next";
import Head from "next/head";
import React from "react";
import { dehydrate, QueryClient } from "react-query";

const DetailPage = () => {
  return (
    <>
      <Head>
        <title>멘투멘 | 상세 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Detail />
    </>
  );
};

export const getServerSideProps = async (ctx: NextPageContext) => {
  const queryClient = new QueryClient();

  if (ctx.query.id) {
    await Promise.all([
      queryClient.prefetchQuery(
        QUERY_KEYS.Post.getPostById(Number(ctx.query.id)),
        () => PostApi.getPostByIdApi(Number(ctx.query.id))
      ),
    ]);
  }

  return {
    id: ctx.query.id as string,
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default DetailPage;
