import Tag from "@/components/Tag";
import { QUERY_KEYS } from "@/queries/queryKey";
import PostRepository from "@/repositories/Post/post.repository";
import { NextPageContext } from "next";
import Head from "next/head";
import { dehydrate, QueryClient } from "react-query";

const TagPage = ({ tag }: { tag: string }) => {
  return (
    <>
      <Head>
        <title>멘투멘 | {tag} 페이지</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tag />
    </>
  );
};

TagPage.getInitialProps = async (ctx: NextPageContext) => {
  const queryClient = new QueryClient();

  if (ctx.query.tag) {
    await Promise.all([
      queryClient.prefetchQuery(
        QUERY_KEYS.Post.getTag(ctx.query.tag as string),
        () => PostRepository.getPostByTag(ctx.query.tag as string)
      ),
    ]);
  }
  return {
    tag: ctx.query.tag as string,
    props: {
      dehydratedState: dehydrate(queryClient),
    },
  };
};

export default TagPage;
